language: cpp
compiler:
    - g++
before_install:
    - sudo apt-get update
    - sudo apt-get install libgtest-dev
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
    - hg clone https://bitbucket.org/eigen/eigen#3.2
before_script:
    - pwd
script: "sh ./test_run.sh"
